### ISSUE TITLE
Next Engine Release: Bind move(rotate,tilt,reset)

### ISSUE THREAD

**Issue by badosu** [springraaar/metal_factions#5]
Next engine release on spring extracts once hardcoded modifiers:

- `moverotate`: Free rotation with alt+mmb drag on spring camera
- `movetilt`: Rotation on x axis with ctrl+mousewheel on overhead and spring camera
- `movereset`: Instant zoomin zoomout on certain camera states with alt pressed

Engine defaults already bind these, and I notice MF uses default engine binds or users binds.

If you wish to force these modifiers to be defined you can:

```
	{    "Any+ctrl",     "movetilt"     }, // rotates the camera over the x axis on mousewheel move
	{    "Any+alt",      "movereset"    }, // resets camera state to maxzoom/minzoom on mousewheel move, additionally resets tilt on Overhead cam
	{    "Any+alt",      "moverotate"   }, // rotates the camera in x and y axis on mmb move (Spring cam)
```

If these modifiers aren't bound they won't be applied.

**Comment by springraaar** [comment]
Thanks for the info.

You mean the BAR105 engine right?

**Comment by badosu** [comment]
Yes, are you using that or plan to continue using it to run your game?

**Comment by badosu** [comment]
I have a planned PR for MF supporting engine passed actions on next engine release, which will avoid a fundamental flaw with lua action handling and optimize/fix keychains/avoid mismatched actions between engine and lua. These changes are counter-productive if you plan to support 106 in the future instead (although can be made non-breaking on lua side).

**Comment by springraaar** [comment]
I plan to change to BAR105 eventually but i'm still using official 105.0 atm. I have no plan to change to the official 106.0.

Either way, divergence between BAR105 and 106.0 is a problem. They should converge!

**Comment by badosu** [comment]
Agree, I'm not sure if that will happen though. 106 is also progressing in their own way

**Comment by badosu** [comment]
Ok, I'll assume MF is not using BYAR105 then
